### ISSUE TITLE
Request for Paper

### ISSUE THREAD

**Issue by kai0416s** [fancj2017/SAS-VAE#1]
Thank you for your outstanding research. However, it seems that I am unable to find the paper at the moment. Could you kindly provide it? Thank you.

**Comment by fancj2017** [comment]
You can download the paper through IEEE at the website:https://ieeexplore.ieee.org/search/searchresult.jsp?newsearch=true&queryText=Scale-Adaptive_Asymmetric_Sparse_Variational_AutoEncoder_for_Point_Cloud_Compression




J. Chen, Y. Zhu, W. Huang, C. Lan and T. Zhao, "Scale-Adaptive Asymmetric Sparse Variational AutoEncoder for Point Cloud Compression," in IEEE Transactions on Broadcasting, vol. 70, no. 3, pp. 884-894, Sept. 2024, doi: 10.1109/TBC.2024.3437161.







--

Yours Sincerely,
 Jian Chen
College of  Physics and Information Engineering,
Fuzhou University,
China






At 2024-09-22 14:55:58, "kai0416s" ***@***.***> wrote:

Thank you for your outstanding research. However, it seems that I am unable to find the paper at the moment. Could you kindly provide it? Thank you.
